<?php

namespace Mrlaozhou\Indulge;

use Illuminate\Database\Eloquent\Model;
use Mrlaozhou\Indulge\Eloquent\Builder;
use Mrlaozhou\Indulge\Observers\IndulgeEloquentObserver;

trait Indulge
{
    use Concerns\Fields,
        Concerns\Providers,
        Concerns\Values,
        Concerns\ShortRent;

    /**
     * @var bool
     */
    protected static $indulged = false;

    public function isIndulged ()
    {
        return static::$indulged;
    }

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        //  boot indulge
        static::bootIndulge();
    }

    /**
     * Boot indulge
     */
    protected static function bootIndulge ()
    {
        static::$indulged   =   true;
        static::observe( IndulgeEloquentObserver::class );
    }

    /**
     *
     * @param $query
     *
     * @return \Illuminate\Database\Eloquent\Builder|\Mrlaozhou\Indulge\Eloquent\Builder
     */
    public function newEloquentBuilder($query)
    {
        if( $this->isIndulged() ) {
            return new Builder($query);
        }
        return new \Illuminate\Database\Eloquent\Builder($query);
    }

    /**
     * @param \Illuminate\Database\Eloquent\Model|null $model
     *
     * @return bool
     */
    public function existsEntity (Model $model=null)
    {
        return !is_null($model) ? $model->exists : $this->exists;
    }

}